[supervisord]
nodaemon=true

[program:app]
command=/opt/conda/envs/appenv/bin/python /app/src/app.py
directory=/app/src
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:collector]
command=/opt/conda/envs/appenv/bin/python /app/src/collector.py
directory=/app/src
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
